version: '2'

services:
  gitlab:
      image: gitlab/gitlab-ce:latest
      ports:
          - "443:443"
          - "80:80"
          - "2222:22"
      networks:
          - devops

  jenkins:
      image: jenkins:latest
      ports:
          - "81:8080"
          - "50000:50000"
      networks:
          - devops
      volumes:
          - /data/jenkins:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
      image: sonarqube
      ports:
          - "9000:9000"
          - "9092:9092"
      networks:
          - devops

networks:
  devops:
    driver: bridge
