apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockerstart.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.dockerstart.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tomcat-service
          servicePort: 80
